version: '3'
services:
  ms-courses:
    build: ./ms-courses
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
      - service-registry
  ms-registrations:
    build: ./ms-registrations
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - rabbitmq
      - service-registry
  ms-students:
    build: ./ms-students
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq
      - service-registry
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
  cloud-gateway:
    build: ./cloud-gateway
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_MULTIPLE_DATABASES="ms-courses","ms-students","ms-registrations"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
